WebUI/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain.ModelView;
using Domain.Repository;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class InvoiceController : BaseController
    {
        private OrderRepository repo = new OrderRepository();
        private OrderView order;
        private OrderSes orderSes = new OrderSes();
        public async Task<ActionResult> Index()
        {
            Menu.ChangeSelected(4, 2);
            Session["Menu"] = Menu;
            Session["ChDetail"] = null;
            Session["OrdSes"] = null;
            Session["Detail"] = null;
            List<OrderV> orders = await repo.GetOrder(Menu.CustId,1);
            return View(orders);
        }
        
        public async Task<ActionResult> CreateFrom(int id)
        {
            order = await repo.GetCopy(id,1);
            order.Invoice = 1;
            orderSes.id = order.OrderId;
            orderSes.act = "Новый счет";
            Session["OrdSes"] = orderSes;
            return RedirectToAction("Booking");
        }
        public async Task<ActionResult> Create()
        {
            order = await repo.GetCreate(Menu.CustId,1);
            orderSes.id = order.OrderId;
            orderSes.act = "Новый счет";
            Session["OrdSes"] = orderSes;
            return RedirectToAction("Booking");
        }
        public ActionResult Edit(int id)
        {
            orderSes.id = id;
            orderSes.act = "Редактировать счет";
            Session["OrdSes"] = orderSes;

            return RedirectToAction("Booking");
        }
        public async Task<ActionResult> Copy(int id)
        {
            order = await repo.GetCopy(id);
            orderSes.id = order.OrderId;
            orderSes.act = "Копировать счет";
            Session["OrdSes"] = orderSes;
            return RedirectToAction("Booking");
        }
        public async Task<ActionResult> Delete(int id)
        {
            order = await repo.GetChange(id);
            orderSes.id = id;
            orderSes.act = "Удаление счета";
            Session["OrdSes"] = orderSes;

            ViewBag.Order = "Удаление счета";
            return View(order);
        }

        [HttpPost]
        public async Task<ActionResult> Delete()
        {
            orderSes = (OrderSes)Session["OrdSes"];
            await repo.Delete(orderSes.id);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Booking()
        {
            orderSes = (OrderSes)Session["OrdSes"];
            order = await repo.GetChange(orderSes.id);
            Session["Detail"] = order.Products;
            ViewBag.Order = orderSes.act;
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Booking(OrderView ord, string Gd, string Adr, string Prs)
        {
            List<OrderProductView> detail = (List<OrderProductView>)Session["Detail"];
            ord.Invoice = 1;
            if (ModelState.IsValid && Gd == null && Adr == null && Prs == null && ord.StatusId == 0)
            {
                ord.StatusId = 1;
            }
            await repo.Save(ord, detail);
            if (Gd != null)
            {
                return RedirectToAction("Index", "Good", new { act = "Detail", cont = "Order" });
            }
            if (Adr != null)
                return RedirectToAction("NewAdres");
            if (Prs != null)
                return RedirectToAction("NewContact");

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> DelDetail(int id)
        {
            Session["ChDetail"] = id;
            OrderProductView detail = await db.OrderProductViews.FindAsync(id);
            return View(detail);
        }
        [HttpPost]
        public async Task<ActionResult> DelDetail()
        {
            int id = (int)Session["ChDetail"];
            OrderProduct prod = await db.OrderProducts.FindAsync(id);
            db.OrderProducts.Remove(prod);
            await db.SaveChangesAsync();
            Session["ChDetail"] = null;
            return RedirectToAction("Index");
        }
        public ActionResult ChDetail(int id, string act)
        {
            Session["ChDetail"] = id;
            return RedirectToAction("Index", "Good", new { act = "Detail", cont = "Order" });
        }
        public async Task<ActionResult> Detail(int id)
        {
            Good good = await db.Goods.FindAsync(id);
            OrderProductView svd = new OrderProductView();
            svd.GoodId = good.GoodID;
            svd.Good = good.txt;
            svd.Unit = good.Unit;
            svd.OrderId = id;
            if (Session["ChDetail"] != null)
            {
                int DetId = (int)Session["ChDetail"];
                Session["ChDetail"] = null;
                svd.OrderProductId= DetId;                
            }
            return View(svd);
        }

        [HttpPost]
        public async Task<ActionResult> Detail(OrderProductView svd)
        {
            orderSes = (OrderSes)Session["OrdSes"];
            if (Session["Detail"] != null)
            {
                await repo.SaveDetail(orderSes.id, svd);
            }
            return RedirectToAction("Booking", "Order", new { id = orderSes.id });
        }

        public ActionResult NewContact()
        {
            Person person = new Person();
            person.CustId = Menu.CustId;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> NewContact(Person person)
        {
            try
            {
                person.CustId = Menu.CustId;
                db.Persons.Add(person);
                await db.SaveChangesAsync();

                orderSes = (OrderSes)Session["OrdSes"];
                order = await repo.GetChange(orderSes.id);
                order.PersonId = person.PersonId;
                await repo.Save(order);
                return RedirectToAction("Booking");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult NewAdres()
        {
            Adres adres = new Adres();
            return View(adres);
        }
        [HttpPost]
        public async Task<ActionResult> NewAdres(Adres adres)
        {
            adres.CustId = Menu.CustId;
            db.Adreses.Add(adres);
            await db.SaveChangesAsync();
            orderSes = (OrderSes)Session["OrdSes"];
            order = await repo.GetChange(orderSes.id);
            order.AdresId = adres.AdresID;
            await repo.Save(order);

            return RedirectToAction("Booking");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
    

WebUI/Views/Invoice/Booking.cshtml
@model Domain.ModelView.OrderView
@{    
    ViewBag.Title = ViewBag.Order; /*+" №  " + Model.OrderId;*/
}
@section metatags
{
    <meta name="description" content="@ViewBag.Title" />
    <meta name="keywords" content="@ViewBag.Title, АБЗ-4" />
    <meta name="robots" content="noindex, nofollow">
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Styles.Render("~/Content/datetimepickercss")
    @Scripts.Render("~/bundles/datetimepickerjs")
}
<div class="row">
    <div class="col-md-12">
        <section id="orderForm" class="client-form">
            @using (Html.BeginForm("Booking", "Invoice", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <fieldset>
                    @Html.HiddenFor(model => model.OrderId)
                    @Html.HiddenFor(model => model.CustId)
                    @Html.HiddenFor(model => model.Dat)
                </fieldset>

                <h2>Заказанные товары</h2>
                <p class="help-block">
                    <input name="Gd" type="submit" value="Добавить товар" class="actionButtons btn btn-xs-sm-md btn-default btn-success" role="button" title="Добавить товар" />
                </p>

                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-grey-header null-margin">
                        <thead>
                            <tr>
                                <th>
                                    Продукция
                                </th>
                                <th>
                                    Ед. изм.
                                </th>
                                <th>
                                    Количество
                                </th>
                                <th>
                                    Управление
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Detail)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Good)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Unit)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Quant)
                                    </td>
                                    <td>
                                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe065;"), "ChDetail", new { id = item.OrderDetailId, act = "Edit" }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Редактировать товар" })
                                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe020;"), "DelDetail", new { id = item.OrderDetailId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Удалить товар" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                @*<h2>Способ получения</h2>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.AdresId, Model.SelectAdres, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
                        <p class="help-block">
                            <input name="Adr" type="submit" value="@HttpUtility.HtmlDecode("&#xe081;")" class="glyphicon actionButtons btn btn-xs-sm-md btn-default glyph-btn" role="button" title="Внести новый адрес" />
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* 
                            * Если вы хотите что бы доставку осуществил АБЗ-4
                            выберите из списка адрес доставки или внесите новый и установите галочку у способа доставки. Иначе снимите галочку со способа доставки.                        </p>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Contract, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.ContractId, Model.SelectContract, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Contract, "", new { @class = "text-danger" })
                    </div>
                </div>
                <h2>Дополнительная информация к счету</h2>
                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control multi-line", @rows = "3" })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                        <p class="help-block">* тут вы можете указать удобное для вас время доставки продукции и другие ваши пожелания</p>
                    </div>
                    @Html.LabelFor(model => model.isOnlinePay, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">                        
                        @Html.CheckBoxFor(model => model.isOnlinePay, new { @class = "form-control checkbox" })
                        <p class="help-block">* тут вы можете указать оплату через интернет</p>
                    </div>
                </div>
                <div>
                    <hr />
                    @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к списку счетов", "Index", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к списку счетов" })
                    &nbsp;&nbsp;&nbsp;
                    <input type="submit" value="Сохранить заказ" class="actionButtons btn btn-xs-sm-md btn-success" />
                </div>
            }
        </section>
    </div>
</div>

WebUI/Views/Invoice/Create.cshtml
@model Domain.ModelView.OrderView
@{
    ViewBag.Title = "Новый заказ";
}
@section metatags
{
    <meta name="description" content="@ViewBag.Title" />
    <meta name="keywords" content="@ViewBag.Title, АБЗ-4" />
    <meta name="robots" content="noindex, nofollow">
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Styles.Render("~/Content/datetimepickercss")
    @Scripts.Render("~/bundles/datetimepickerjs")
}
<div class="row">
    <div class="col-md-12">
        <section id="orderForm" class="client-form">
            @using (Html.BeginForm("Create", "Order", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <fieldset>
                    @Html.HiddenFor(model => model.OrderId)
                    @Html.HiddenFor(model => model.CustId)
                </fieldset>
                <h2>Заказанные товары</h2>

                @*<p>
                    @Html.ActionLink(HttpUtility.HtmlDecode("&#xe081;"), "NewDetail", new { order =Model }, new { @class = "actionButtons btn btn-default glyphicon glyph-btn", @role = "button", @title = "Добавить в заказ еще товар" })
                </p>*@

                <p align="center">
                    <input class="actionButtons btn btn-xs-sm-md btn-success"  name="Gd" type="submit" value="Добавить товар" />
                </p>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-grey-header null-margin">
                        <thead>
                            <tr>
                                <th>
                                    Продукция
                                </th>
                                <th>
                                    Ед. изм.
                                </th>
                                <th>
                                    Количество
                                </th>
                                <th>
                                    Управление
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Detail)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Good)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Unit)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Quant)
                                    </td>
                                    <td>
                                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe065;"), "ChDetail", new { id = item.OrderDetailId, act = "Edit" }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Редактировать товар" })
                                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe020;"), "DelDetail", new { id = item.OrderDetailId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Удалить товар" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                <h2>Выберите дату</h2>
                <div class="form-group">
                    @Html.LabelFor(m => m.Dat, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Dat, new { @class = "form-control datefield", @type = "text" })
                        @Html.ValidationMessageFor(m => m.Dat, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr />
                <h2>Способ получения</h2>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.Centr, htmlAttributes: new { @class = "col-md-3 control-label" })
                        <div class="col-md-9">
                            @Html.CheckBoxFor(model => model.Centr, new { @class = "form-control checkbox" })
                            @Html.ValidationMessageFor(model => model.Centr, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.AdresId, Model.SelectAdres, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
                        <p class="help-block">
                            <input name="Adr" type="submit" value="@HttpUtility.HtmlDecode("&#xe081;")" class="glyphicon actionButtons btn btn-xs-sm-md btn-default glyph-btn" role="button" title="Внести новый адрес" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* Если вы хотите что бы доставку осуществил АБЗ-4
                            выберите из списка адрес доставки или внесите новый. Иначе выберите Самовывоз.
                        </p>
                    </div>
                </div>
                <hr />
                <h2>Данные клиента для заказа</h2>
                <div class="form-group">
                    @Html.LabelFor(model => model.Contract, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.ContractId, Model.SelectContract, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Contract, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Person, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.PersonId, Model.SelectPerson, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Person, "", new { @class = "text-danger" })
                        <p class="help-block">
                            <input name="Prs" type="submit" value="@HttpUtility.HtmlDecode("&#xe081;")" class="glyphicon actionButtons btn btn-xs-sm-md btn-default glyph-btn" role="button" title="Внести новый контакт" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* выберите из списка контакт или внесите новый"
                        </p>
                    </div>
                </div>
                <hr />
                <h2>Дополнительная информация к заказу</h2>
                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control multi-line", @rows = "3" })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                        <p class="help-block">* тут вы можете указать удобное для вас время доставки продукции и другие ваши пожелания</p>
                    </div>
                </div>
                <p>&nbsp;</p>
                <p align="center">
                    <input class="actionButtons btn btn-xs-sm-md btn-success" type="submit" value="Сохранить заказ" />
                </p>
            }
            <hr />
            <div>

                @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к списку заказов", "Index", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к списку заказов" })
            </div>
        </section>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#Dat').datetimepicker({
            locale: 'ru', format: 'DD.MM.YYYY'
        });
    });
</script>
@*<script type="text/javascript">
    if (!Modernizr.inputtypes.date) {
        $(function () {
            $("input[type='date']")
                .datetimepicker({
                    locale: 'ru',
                    format: 'DD.MM.YYYY'
                })
                .get(0)
                .setAttribute("type", "text");
        })
    };
</script>*@

WebUI/Views/Invoice/DelDetail.cshtml
@model Domain.Entities.OrderDetailView

@{
    ViewBag.Title = "Удаление продукции";
}

<h3>Вы уверены что надо удалить продукцию?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Good)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Good)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quant)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К списку заказов", "Index")
        </div>
    }
</div>

WebUI/Views/Invoice/Delete.cshtml
@model Domain.ModelView.OrderView
@{
    ViewBag.Title = "Удаление заказа №" +Model.OrderId;
}

<h3>Вы уверены что хотите удалить этот заказ?</h3>
<div class="row">
    <div class="col-md-12">
        <section id="orderForm" class="client-form">
                <div class="form-group">
                    @Html.LabelFor(m => m.Dat, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DisplayFor(m => m.Dat, new { @class = "form-control datefield", @type = "text" })
                    </div>
                </div>
                <hr />
                <h2>Заказанные товары</h2>

                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-grey-header null-margin">
                        <thead>
                            <tr>
                                <th>
                                    Продукция
                                </th>
                                <th>
                                    Ед. изм.
                                </th>
                                <th>
                                    Количество
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Detail)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Good)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Unit)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Quant)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <hr />

                <div class="form-group">
                    @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DisplayFor(model => model.Adres)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Contract, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DisplayFor(model => model.Contract)
                    </div>
                </div>
                @*<div class="form-group">
                    @Html.LabelFor(model => model.Person, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.DisplayFor(model => model.Person)
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control multi-line", @rows = "3" })
                    </div>
                </div>
            
            <hr />

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Удалить" class="btn btn-default" /> 
                 
                </div>
            }
            <div>

                @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к списку заказов", "Index", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к списку заказов" })
            </div>
        </section>
    </div>
</div>

@*<div>
    <h4>VShip</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Good)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Good)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Centr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Centr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

WebUI/Views/Invoice/NewAdres.cshtml
@model Domain.Entities.Adres

@{
    ViewBag.Title = "Новый адрес";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.txt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.txt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.txt, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <hr />
            @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к счету", "Booking", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к счету" })
            &nbsp;&nbsp;&nbsp;
            <input type="submit" value="Сохранить" class="actionButtons btn btn-xs-sm-md btn-success" />
        </div>
    </div>
}