WebUI/Controllers/GoodController.cs
using Domain.Entities;
using Domain.Repository;
using System.Linq;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class GoodController : Controller
    {
        private GoodRepository repo = new GoodRepository();
        private static int pagesize = 20;          // Items count on one page
        private static int vsblpagescount = 10;    // Visible page numbers in page navigator central list 
        private AbzContext db = new AbzContext();
        
        public ActionResult Index(string act,string cont,int categid = 2, int pageNum = 0 )
        {
            ViewBag.MenuItem = "good";
            ViewBag.MenuId = categid;
            ViewBag.ProductDetail = false;
            GoodList goodlist = new GoodList();
            var countitems = repo.GetCountItems(categid);
            goodlist.CategId = categid;
            goodlist.CategName = db.Categs.Find(categid).txt;
            goodlist.PageInfo = new PageInfo { pageNum = pageNum, itemsCount = countitems, pageSize = pagesize, vsblPagesCount = vsblpagescount };
            goodlist.Products = repo.GetSkipTake(pageNum * pagesize, pagesize, categid).ToList();
            if (act != null)
            {
                goodlist.Action = act;
                goodlist.Controller = cont;
                Session["gl"] = goodlist;
            }
            else
            {
                GoodList gl = (GoodList)Session["gl"];
                goodlist.Action = gl.Action;
                goodlist.Controller = gl.Controller;
            }
            return View(goodlist);
        }
        public ActionResult CategoryMenu(string menuName, int? menuId)
        {
            var assortmentMenu = new AssortmentMenu();
            assortmentMenu.Categs = db.Categs;
            assortmentMenu.MenuName = menuName;
            assortmentMenu.MenuId = menuId;
            return PartialView(assortmentMenu);
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
﻿<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        @RenderSection("metatags", false)
        <meta name="author" content="KADMII" />
        <title>@ViewBag.Title – Личный кабинет АБЗ-4</title>
        @Scripts.Render("~/bundles/fontloader")
        <link href="/images/favicon.ico" rel="shortcut icon" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/maincss")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryui", "~/bundles/jqueryval", "~/bundles/modernizr")
    </head>
    <body>
        <header class="hidden-print">
            <div class="navbar navbar-default navbar-static-top header-wrapper" role="navigation">
                <div class="container-fluid hidden-xs top-login-wrapper">
                    <div class="container">
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
                <div class="container visible-xs">
                    <div class="navbar-header">
                        @if (Request.IsAuthenticated)
                        {
                            <button type="button" class="navbar-toggle btn-main-menu-xs" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        }
                        <a class="navbar-brand logo-brand-xs" href="/Home" title="Открытое Акционерное Общество Асфальто-Бетонный Завод № 4 'КАПОТНЯ'">
                            АБЗ&nbsp;&nbsp;4&nbsp;&nbsp;<b>КАПОТНЯ</b>
                        </a>
                    </div>
                </div>
                <div class="container hidden-xs">
                    <div class="row">
                        <a class="navbar-brand logo-brand col-sm-5 col-lg-4" href="/Home" title="Открытое Акционерное Общество Асфальто-Бетонный Завод № 4 'КАПОТНЯ'">
                            <img src="/images/logo.png" width="294" height="54" alt="Открытое Акционерное Общество Асфальто-Бетонный Завод № 4 'КАПОТНЯ'"
                                 title="Открытое Акционерное Общество Асфальто-Бетонный Завод № 4 'КАПОТНЯ'">
                            <span class="logo-title">Личный&nbsp;&nbsp;&nbsp;кабинет</span>
                        </a>
                        @if (Request.IsAuthenticated)
                        {
                            @Html.Action("HeadMenu", "Custs")
                        }
                    </div>
                </div>
                @if (Request.IsAuthenticated)
                {
                    Html.RenderAction("MainMenu", "Custs", null);
                }
            </div>
        </header>
        <div class="container body-content content-wrapper">
            <div class="row">
                @if (ViewBag.MenuItem != "good")
                {
                    <h1>@ViewBag.Title</h1>
                    <div class="content-block col-md-12" style="@Html.Encode(Request.IsAuthenticated == false ? "padding-top:0;padding-bottom: 0;" : "")">
                        @RenderBody()
                    </div>
                }
                else
                {
                    { Html.RenderAction("CategoryMenu", "Good", new { menuName = ViewBag.MenuItem, menuId = ViewBag.MenuId }); }
                    <div class="col-xs-12 col-sm-12 col-md-9 product-content-wrapper">
                        <h1>@ViewBag.Title</h1>
                        <div class="content-block product-content @Html.Encode(ViewBag.ProductDetail == false ? "null-padding" : "") ">
                            @RenderBody()
                        </div>
                    </div>
                }
            </div>
        </div>
        <footer class="footer-wrapper hidden-print">
            @{ Html.RenderPartial("~/Views/Home/FooterMenu.cshtml"); }
            <div class="container-fluid footer-bottom-wrapper">
                <div class="container clearfix footer-bottom">
                    <p class="footer-copyright-info">&copy;&nbsp;@DateTime.Now.Year.&nbsp;&nbsp;ОАО АБЗ-4&nbsp;&quot;КАПОТНЯ&quot;&nbsp;&nbsp;<span class="hidden-xs">Все права защищены.</span></p>
                </div>
            </div>
        </footer>
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>